port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "32769"
  password: "postgrespw"
  dbname: "postgres"
  sslmode: "disable"

colors:
  white: "#ffffff"
  blue: "#3248a8"
  cyan: "#19ffd9"
  purple: "#8c19ff"
  red: "#ff1919"
  green: "#19ff75"
  salad: "#19ff3b"
  orange: "#ffb619"
  yellow: "#ffec19"
